# Uncomment this line to define a global platform for your project
platform :osx, '10.9'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OSX+SQLiteModel' do

pod 'SQLiteModel'

end

